name: Docker Build & Push

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

jobs:
  build-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
        include:
          - platform: linux/amd64
            GOARCH: amd64
          - platform: linux/arm64
            GOARCH: arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ matrix.platform }}
          build-args: |
            ACTIVE=${{ github.event_name == 'push' && 'prod' || 'dev' }}
            GOARCH=${{ matrix.GOARCH }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/echo-gin:${{ github.sha }}
            ${{ github.ref == 'refs/heads/main' && (secrets.DOCKERHUB_USERNAME + '/echo-gin:latest') || '' }}
            ${{ startsWith(github.ref, 'refs/tags/') && (secrets.DOCKERHUB_USERNAME + '/echo-gin:' + github.ref_name) || '' }}
          push: ${{ github.event_name != 'pull_request' }}