server:
  port: 9100

spring:
  application:
    name: cabinet.java
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:pgsql://127.0.0.1:5432/drinkice
    username: root
    password: zxczxc

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.example.cabinet.model
  configuration:
    map-underscore-to-camel-case: true
