name: echo.gin

on:
  workflow_dispatch:
  push:
    paths:
      - 'v-echo/echo.gin/**'

env:
  WORKSPACE: 'v-echo/echo.gin'
  IMAGE_NAME: 'ghcr.io/lkzc19/echo_gin'

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
        include:
          - platform: linux/amd64
            GOARCH: amd64
          - platform: linux/arm64
            GOARCH: arm64

    steps:
      - uses: actions/checkout@v4
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: 'Login to GHCR'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.WORKSPACE }}
          platforms: ${{ matrix.platform }}
          # build-args: |
          #   GOARCH=${{ matrix.GOARCH }}
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest