name: loafer.java

on:
  workflow_dispatch:
  push:
    paths:
      - 'v-loafer/loafer.java/**'

env:
  WORKSPACE: 'v-loafer/loafer.java'
  IMAGE_NAME: 'ghcr.io/lkzc19/loafer.java'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: 'Set up JDK 17'
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: 'Package gradle project'
        run: |
          cd ${{ env.WORKSPACE }}
          ./mvnw package -Dmaven.test.skip=true
      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v2
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Build and push docker image'
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.WORKSPACE }}
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
